### ISSUE TITLE
Move to cloud build

### ISSUE THREAD

**Issue by kvokka** [replaygaming/go-eventsource#21]
This is "do not forget" sort of task.

After the merge of #20 we need to remove codeship integration in favor of cloud build.

I'm still trying to figure out how to do it in the github interface (but can do it only for personal repos).

@orifito

**Comment by orifito** [comment]
I guess it's because lack of rights/permissions? Apparently I can't manage integrations neither.
@d-Pixie could you check for us please?

**Comment by kvokka** [comment]
Thank you @orifito . By the way it was a but of confusing, since when you are admin almost everywhere you may kinda forget that something may be hidden from you :)

**Comment by d-Pixie** [comment]
I have access to remove it. Ping me when you want it gone :)

**Comment by kvokka** [comment]
@d-Pixie ping :)

**Comment by kvokka** [comment]
Regarding #23 everything works with cloud build. yeey
