### ISSUE TITLE
Helm integration plan with out downtime

### ISSUE THREAD

**Issue by kvokka** [replaygaming/go-eventsource#26]
After googling/trying/playing and suffering was found hack, which should allow us to integrate helm with `es` (and not only it). i tried it with `ondemand` ns, and it worked.

```bash
$ kgs eventsource -o yaml > svc.yaml
$ kgd eventsource -o yaml > dep.yaml

$ kubectl -n ondemand apply -f svc.yaml
$ kubectl -n ondemand apply -f dep.yaml

# on the first run command will return an error. Just run it one more time and now you adopted the resources by helm. 
$ helm upgrade --install --force --namespace=ondemand -f charts/go-eventsource/values.staging.ondemand.yaml eventsource-ondemand charts/go-eventsource
$ helm upgrade --install --force --namespace=ondemand -f charts/go-eventsource/values.staging.ondemand.yaml eventsource-ondemand charts/go-eventsource
```

After we'll be able to use resources as usual.

wdyt @orifito ?

**Comment by orifito** [comment]
I've tested the hack on the `akn` namespace, bad news... :__( 
The trick is the `--force` on the second helm upgrade, which "forces resource update through delete/recreate" of all k8s resources.
Regarding the deployment, we can't be sure new pods are ready before old ones are terminated, since the pod disruption budget fails with (all are terminated at once):
```
[...]
Warning  NoControllers                    26s (x4 over 27s)  controllermanager  found no controllers for pod "eventsource-db65c49d4-4szr4"
Warning  CalculateExpectedPodCountFailed  26s (x4 over 27s)  controllermanager  Failed to calculate the number of expected pods: found no controllers for pod "eventsource-db65c49d4-4szr4"
```

And, more importantly, the service is also recreated, so there's a new ingress backend service for it. This leads to 5 mins of downtime with 502s.

**Comment by kvokka** [comment]
@orifito  You r right. And the key here is not only `--force` flag. It was too late yesterday when i found it and did not checked the re-creation, so it is great that you found it.

Yes, the resources will be re-created, even when you do not use `--force` flag, just checked.

There is no problem to over-provision pods here with extra deployment (add to each of them some extra label, like `provisioner: script` and `provisioner: helm`, keep the service the same, so it will cover the pdb missing failure)

But we can add ingress for `es` and use another path for it, which does not intersect with the old paths (rails are using `es.s1farm.com` for staging and `eventsource.replaypoker.com` for prod, not very convenient. we'll use, for example `events.foo.com`)

The same thing was already done for `poker-api`.

**Comment by orifito** [comment]
Ah, I tested and it didn't recreate without the `--force`...
Anyway let's have a chat later today about all this k8s resources overprovisioning, I'm a bit lost now, specilaly with the "keep the service name" part.

**Comment by kvokka** [comment]
It became interesting for me to check, and I tried to re-provision a service with type `NodePort` (removing first all information, which were filled by k8s) and got :

```
The Service "rails" is invalid:
* metadata.resourceVersion: Invalid value: "": must be specified for an update
* spec.clusterIP: Invalid value: "": field is immutable
* spec.ports[0].nodePort: Forbidden: may not be used when `type` is 'ClusterIP'
```

And it is right! And i remembering now, that services are only party changeable. So you can add label or annotation, but u can not change a lot of fields inside.

The best next step is to provision rails with helm and do the switch, as was discussed today in DM.

**Comment by orifito** [comment]
No longer required.
